site_name: "Wiki - Life Santos"
# site_description: "Documentation complÃ¨te sur les diffÃ©rents domaines."
site_author: "Noah FOURNIER"

theme:
  name: material
  logo: images/lifesantos.png
  favicon: images/lifesantos.png
  language: fr
  locale: fr
  palette:
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: "Passer en mode sombre"
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: "Passer en mode clair"
  font:
    text: Roboto
    code: Roboto Mono
  features:
    # - navigation.tabs
    - navigation.top
    # - navigation.expand
    - navigation.footer
    - toc.integrate
    - search.highlight
    - search.suggest
    - navigation.instant
    # - navigation.sections

nav:
  - "ğŸ  Accueil": index.md
  - "ğŸ“š RÃ¨glements": 
      - "ğŸ“– RÃ¨glement Global": reglements/reglement.md
      - "ğŸ”« RÃ¨glement IllÃ©gal": reglements/illegal.md
      - "ğŸš“ RÃ¨glement FDO": reglements/fdo.md
  - "â„¹ï¸ Introduction": introduction.md
  - "ğŸ“œ GÃ©nÃ©ralitÃ©s": generalites.md
  - "âŒ¨ï¸ Touches": 
      - "ğŸ“ƒ Liste": touches/liste.md
  - "ğŸ’» Commandes": commandes/liste.md
  - "ğŸŒ Ressources":
      - "â„¹ï¸ Introduction" : ressources/introduction.md
      - "ğŸ†˜ Appel d'urgence" : ressources/appel-urgence.md
      - "ğŸ’ Bien dÃ©buter": ressources/bien-debuter.md
      - "ğŸ›’ Boutique" : ressources/boutique.md
      - "ğŸ“± Cartes SIM" : ressources/cartes-sim.md
      - "ğŸ¢ Entreprises" : ressources/entreprises.md
      - "ğŸ”« IllÃ©gal" : ressources/illegal.md
      - "ğŸ“• Lexique" : ressources/lexique.md
      - "ğŸ’¼ Les mÃ©tiers" : ressources/metiers.md
      - "ğŸ“¦ Limite d'objets" : ressources/limite-objets.md
      - "ğŸš« Objets bloquÃ©s" : ressources/objets-bloques.md
      - "ğŸ‘¨â€ğŸ¦± Personnages" : ressources/personnages.md
      - "ğŸ”§ RÃ©paration de vÃ©hicule" : ressources/reparation-vehicule.md
      - "ğŸ› ï¸ Sanctions" : ressources/sanctions.md
      - "ğŸ“¢ Services publics" : ressources/services-publics.md
      - "ğŸ  Terrains" : ressources/terrains.md
      - "ğŸ“© Tickets" : ressources/tickets.md
      - "ğŸ‘• Upload" : ressources/upload.md
      - "ğŸ™ï¸ La ville": ressources/ville.md
      - "ğŸ›¡ï¸ Zones Safe" : ressources/zones-safe.md
  - "â“ FAQ": faq.md


markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/lifesantos
  generator: false

copyright: "Copyright Â© 2025 Life Santos"